PATCH /api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/awards/c50fc56b3aa14fcc8dcc95d9498710f5?acc_token=f95bff6de12b4f01a05b7f1de88b4b34 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "cancelled"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "cancelled", 
    "complaintPeriod": {
      "startDate": "2017-10-11T12:57:48.582436+03:00", 
      "endDate": "2017-10-11T12:57:48.821418+03:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137256", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "bid_id": "8c99919d866948839e883c7d8440ec3e", 
    "value": {
      "currency": "UAH", 
      "amount": 469.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2017-10-11T12:57:48.831407+03:00", 
    "id": "c50fc56b3aa14fcc8dcc95d9498710f5"
  }
}

