PATCH /api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/contracts/dd8330681e1a4f26bed059ab6048b7b6?acc_token=d31a937417d947c88d8130d9215c919b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 80
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "status": "active", 
    "dateSigned": "2017-10-11T12:57:50.238782+03:00"
  }
}


200 OK
Content-Type: application/json; charset=UTF-8

{
  "data": {
    "status": "active", 
    "documents": [
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4472d48e3f93427e94dc1738b77868aa?KeyID=020ebf5f&Signature=UtnKx87CsKzf5iAdY%252BFCsg%252B79YoZAgtiOxgnhfaZzySCl4x%252B6Flf18hQpIQ9I6sAMeymKE9We6A1j1ZhNP5yCw%253D%253D", 
        "title": "contract_first_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-10-11T12:57:49.854856+03:00", 
        "dateModified": "2017-10-11T12:57:49.854902+03:00", 
        "id": "8efadc58a9db4c5ebbaa79361cc7e435"
      }, 
      {
        "hash": "md5:00000000000000000000000000000000", 
        "format": "application/msword", 
        "url": "http://public.docs-sandbox.ea.openprocurement.org/get/61c0a70a021c448f8b6f414d21c9f122?KeyID=020ebf5f&Signature=4F8AOjd6wBE1c2WUQQsSpvyhWcbXdf6%252BwEfR%252BiBTow%252Bd0TdM8R9L8SdkZvQ9eEsNaPXx9CiP1zHmO9VEBjeCBw%253D%253D", 
        "title": "contract_second_document.doc", 
        "documentOf": "tender", 
        "datePublished": "2017-10-11T12:57:50.068021+03:00", 
        "dateModified": "2017-10-11T12:57:50.068047+03:00", 
        "id": "95942013577947889fd9e896b590b66a"
      }
    ], 
    "items": [
      {
        "description": "Земля для військовослужбовців", 
        "classification": {
          "scheme": "CAV", 
          "description": "Земельні ділянки", 
          "id": "06000000-2"
        }, 
        "address": {
          "postalCode": "79000", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }, 
        "id": "3b35dd9f674e44059f1c4fbb8c11a739", 
        "unit": {
          "code": "44617100-9", 
          "name": "item"
        }, 
        "quantity": 5
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "aagt@gmail.com", 
          "telephone": "+380 (322) 91-69-30", 
          "name": "Андрій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00137226", 
          "uri": "http://www.sc.gov.ua/"
        }, 
        "name": "ДКП «Книга»", 
        "address": {
          "postalCode": "79013", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 34", 
          "region": "м. Львів", 
          "locality": "м. Львів"
        }
      }
    ], 
    "period": {
      "startDate": "2017-10-11T12:57:40.602343+03:00", 
      "endDate": "2018-10-11T12:57:40.602343+03:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 479.0, 
      "valueAddedTaxIncluded": true
    }, 
    "dateSigned": "2017-10-11T12:57:50.238782+03:00", 
    "date": "2017-10-11T12:57:50.335198+03:00", 
    "awardID": "6b48914d9d81462a95aa87dff79198f1", 
    "id": "dd8330681e1a4f26bed059ab6048b7b6", 
    "contractID": "UA-EA-2017-10-11-000001-1"
  }
}

