POST /api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/awards/6b48914d9d81462a95aa87dff79198f1/documents?acc_token=b466022717a848ca9ba03dacf24508ba HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 379
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9b91133a0a6940bc8ad9fd791c5198ff?KeyID=020ebf5f&Signature=0CT3kEBOWc6EytvsfbJp2LFkl8Nrk5f5cPpx7bpS7ZB%2B5UEfzG0vVtsYmh%2FRcvIeBZpXYa78Sf6CZM5Feof7AA%3D%3D", 
    "title": "SignedAuctionProtocol.pdf", 
    "format": "application/pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "documentType": "auctionProtocol"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/awards/6b48914d9d81462a95aa87dff79198f1/documents/8196ee8f7ca14cf78cb67d7a61557789

{
  "data": {
    "dateModified": "2017-10-11T12:57:48.992259+03:00", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9b91133a0a6940bc8ad9fd791c5198ff?KeyID=020ebf5f&Signature=uDr98ViETfLfGDku8CdsQnPyXzSiWz7G9YEZyNW4eXE8bTM1NTiDh2MS5WcICnzjviQAanTWTCWkh2e0dgIaDg%253D%253D", 
    "author": "bid_owner", 
    "documentOf": "tender", 
    "datePublished": "2017-10-11T12:57:48.992231+03:00", 
    "documentType": "auctionProtocol", 
    "title": "SignedAuctionProtocol.pdf", 
    "id": "8196ee8f7ca14cf78cb67d7a61557789"
  }
}

