POST /api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/documents?acc_token=d31a937417d947c88d8130d9215c919b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 340
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3ee289436f48477697e4274b12fd1074?KeyID=020ebf5f&Signature=TEoIQm5v9KAyopiFwzh4S%2FpPJles6QGiJ54wSc2gBUdPdW%2BrouNo7KWWtEnKFhiMF8G382EelvuFVkiep2%2B%2BBw%3D%3D", 
    "title": "AwardCriteria.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/documents/fc2bca86b36f4d4694cbee956dd40914

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/3ee289436f48477697e4274b12fd1074?KeyID=020ebf5f&Signature=9iDt9YWjl5HjjfhMYtiDpjeWFE5J4SMH8g%2FdrZSO0gb31pGFYSrHbosUe0mCe3n%252BrToGdHa9MBHAqJvFlyK1Bw%253D%253D", 
    "title": "AwardCriteria.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-10-11T12:57:46.782930+03:00", 
    "dateModified": "2017-10-11T12:57:46.782968+03:00", 
    "id": "fc2bca86b36f4d4694cbee956dd40914"
  }
}

