POST /api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/documents?acc_token=d31a937417d947c88d8130d9215c919b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 426
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "title": "third_illustration.jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4fb223f67a754db0838844bf624c5d16?KeyID=020ebf5f&Signature=VhxyBJHYSTBvQz6Dx5QryCEkBnkZIjxElQQJJiE0vNh6BWNKrFre7bfZ9D9Nct3JdwQKplxdbPAYvt1le8s2AA%3D%3D", 
    "format": "image/jpeg", 
    "documentType": "illustration"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/documents/68c3ae0cdacf41bb95dcaf97137e1039

{
  "data": {
    "index": 2, 
    "hash": "md5:00000000000000000000000000000000", 
    "description": "Third illustration description", 
    "format": "image/jpeg", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/4fb223f67a754db0838844bf624c5d16?KeyID=020ebf5f&Signature=OKie9rKYMHaQdSrk77P2jxA2kuSAfY5HAfj8VwbYY8lLiHT9CRtSghoIectn3g%2FksCu1a4yzwaVRpG%2FiaimnDw%253D%253D", 
    "title": "third_illustration.jpeg", 
    "documentOf": "tender", 
    "datePublished": "2017-10-11T12:57:47.097620+03:00", 
    "documentType": "illustration", 
    "dateModified": "2017-10-11T12:57:47.097647+03:00", 
    "id": "68c3ae0cdacf41bb95dcaf97137e1039"
  }
}

