POST /api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/cancellations/e8ffba3981e44421b8b343513e2e3c0f/documents?acc_token=d31a937417d947c88d8130d9215c919b HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 335
Content-Type: application/json
Host: api-sandbox.ea.openprocurement.org

{
  "data": {
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9f7db1f77eb94523b9f009641a6d7493?KeyID=020ebf5f&Signature=fwnGHx8Fh0uz%2FGQpv%2Fk%2FKneH%2BKcaUWvUDiRoWq4aJv77ZVK11viTBR3X0DdvjKad1vVyNDDiLMmoNEAEQe%2FeAw%3D%3D", 
    "title": "Notice.pdf", 
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf"
  }
}


201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.ea.openprocurement.org/api/2.3/auctions/826ce0aeaf9a408487a657a5820b7c01/cancellations/e8ffba3981e44421b8b343513e2e3c0f/documents/6a32af456f3f4af180b66ba39720e8d5

{
  "data": {
    "hash": "md5:00000000000000000000000000000000", 
    "format": "application/pdf", 
    "url": "http://public.docs-sandbox.ea.openprocurement.org/get/9f7db1f77eb94523b9f009641a6d7493?KeyID=020ebf5f&Signature=VaenSeKCrzrTP0YptJqVDePtdgMIV2imywLyp3priXoC5bR8C7mdtI3j7uphDaLphJEw8jlXi0ZHxLjsBPT6CA%253D%253D", 
    "title": "Notice.pdf", 
    "documentOf": "tender", 
    "datePublished": "2017-10-11T12:57:50.734862+03:00", 
    "dateModified": "2017-10-11T12:57:50.734888+03:00", 
    "id": "6a32af456f3f4af180b66ba39720e8d5"
  }
}

